---
# tasks file for roles/http
- name: Run HTTPD
  community.docker.docker_container:
    name: httpd
    image: schtoukai/http
    state: started
    pull: true
    ports:
      - "80:80"
    networks:
      - name: app-network
