version: '3.7'

services:
    backend:
        container_name: simpleappwbdd
        build: ../Backend1/.
        networks:
         - my-network
        depends_on:
         - database

    database:
        container_name: postgres
        build: ../DB/.
        volumes:
         - ./data:/var/lib/postgresql/data
        networks:
         - my-network

    httpd:
        build: ../HTTP/.
        container_name: httpd
        ports:
         - 80:80
        networks:
         - my-network
        depends_on:
         - backend
         - database

networks:
    my-network: 
     external:
      name: app-network
