version: '3.7'

services:
    backend:
        container_name: simpleappwbdd
        build: ../JavaBDD/simple-api-student-main/simple-api-student-main/.
        networks:
         - my-network
        depends_on:
         - database

    database:
        container_name: postgres
        build: ../.
        volumes:
         - ../data:/var/lib/postgresql/data
        networks:
         - my-network

    httpd:
        build: ../HTTPServer/.
        ports:
         - 80:80
        networks:
         - my-network
        depends_on:
         - backend
         - database

networks:
    my-network: 
     external:
      name: app-network
