---
# tasks file for roles/backend
  - name: Run Backend
    community.docker.docker_container:
      name: simpleappwbdd
      state: started
      image: schtoukai/simple-api
      networks:
        - name: app-network

