---
name: CI devops 2023
on:
  push:
    branches:
      - main
      - develop
  pull_request: null
jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.5.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin
          cache: maven
      - name: Build and test with Maven
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=R-Larue_louni-larue_DevOps_S8
          -Dsonar.organization=r-larue -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} --file ./Backend1/pom.xml
  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{
          secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build image and push backend1
        uses: docker/build-push-action@v3
        with:
          context: ./Backend_1
          tags: ${{secrets.DOCKER_USERNAME}}/simple-api1
          push: ${{ github.ref == 'refs/heads/main' }}
      - name: Build image and push backend2
        uses: docker/build-push-action@v3
        with:
          context: ./Backend_2
          tags: ${{secrets.DOCKER_USERNAME}}/simple-api2
          push: ${{ github.ref == 'refs/heads/main' }}
      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./DB
          tags: ${{secrets.DOCKER_USERNAME}}/db
          push: ${{ github.ref == 'refs/heads/main' }}
      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./HTTP
          tags: ${{secrets.DOCKER_USERNAME}}/http
          push: ${{ github.ref == 'refs/heads/main' }}
